name: Check

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: Load action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run:  touch /tmp/src/simple-0.0.0.fc39.src.rpm
      - uses: ./
        with:
          chroot: fedora-39-x86_64
          srpm: /tmp/src/simple-0.0.0.fc39.src.rpm
