name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  srpm:
    name: Build srpm
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v4
      - run: |
          dnf install -y rpmdevtools
          RUN mkdir -p /tmp/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
          rpmbuild -bs -D "_topdir /tmp/rpmbuild" simple.spec
        working-directory: test/simple
      - name: Upload srpm
        uses: actions/upload-artifact@v3
        with:
          name: srpm-artifacts
          path: |
            /tmp/rpmbuild/SRPMS/*

  rpm:
    needs: [ srpm ]
    name: Build rpm with mock-rpm action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download srpm
        uses: actions/download-artifact@v3
        with:
          name: srpm-artifacts
          path: /tmp/src
      - uses: ./
        with:
          chroot: fedora-39-x86_64
          srpm: /tmp/src/simple-0.0.0.fc39.src.rpm
